### ISSUE TITLE
Comment metadata command

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os/plugins-wishlist#12]
The bot comment metadata system is very useful for error logs, but sometimes the error logs dont show enough information and this should be fixed.

[See source code](https://github.com/ubiquity/ubiquibot/blob/8aaf055c091cc3e7f2b42c9f1cf88f45b1d86d17/src/handlers/shared/structured-metadata.ts)

**Comment by 0x4007** [comment]
> Because either way the metadata is readable by everyone afaik

No only collaborators. Metadata can have sensitive information. 

> we could benefit from formatting, copy paste etc

The idea for metadata was that it is intended to be easily parsable by diagnostics tools.

**Comment by gentlementlegen** [comment]
@0x4007 All right makes sense. I think a nice to have would be to add the url related to the Action Run or Supabase logs if any, to avoid looking for the related run. Will look into it.

**Comment by 0x4007** [comment]
> add the url related to the Action Run

Agreed but it wasn't super easy to implement.

**Comment by gentlementlegen** [comment]
Now that the package https://github.com/ubiquity/ubiquibot-logger has been updated to be decoupled from the `Probot` used in v1, I think this task because easier. However, this package has to be included in every plugin created until now, so quite tedious.

The new logger is able to produce pretty logs and the metadata, that would need to be posted with the comments.

**Comment by Keyrxng** [comment]
This is the last item in https://github.com/ubiquibot/plugins-wishlist/issues/5 after https://github.com/ubiquibot/assistive-pricing/pull/18 

Is it possible to refine this spec a bit further I think it seems outdated

Essentially this is going to work in unison with `ubiquibot-logger` and is responsible for posting hidden HTML comments for typically errors but I guess any type of bot comment?

> add the url related to the Action Run

What's the case for if it's a worker?

> No only collaborators. Metadata can have sensitive information.

I remember mentioning that an org could have a private storage repo that plugins could use as their storage solution, it could also include error logs which seems like a good solution here but I know originally the idea wasn't so attractive.

I see that this is enforced via the UI tho which is good, is it enforce at the API level too?

**Comment by Keyrxng** [comment]
>  is it enforced at the API level too?

It is not

**Comment by 0x4007** [comment]
I am open to enforcing "as a best practice" that we don't post sensitive information with the logger but seems a bit risky.

**Comment by gentlementlegen** [comment]
Metadata should be handled on a plugin basis because not every plugin posts comments to GitHub. And eventually posting itself can fail, which in such case should be handled by the kernel that should register the error within out Supabase instance (these is a task for that in the kernel). I added metadata to `conversation-rewards` comments but I guess this ticket is applicable to any plugin / worker posting comments.

**Comment by gentlementlegen** [comment]
I think now that we started developing a SDK, it would be a good fit there. The problem with v1 is that it used an `exec` to get the HEAD sha, but exec is forbidden in workers for security reasons.

**Comment by 0x4007** [comment]
@whilefoo can you get on the SDK?
