### ISSUE TITLE
Telegram GitHub Issue "Workroom"

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/plugins-wishlist#25]
I realize that some projects require collaboration, and our team has a natural tendency to direct message each other. The problem with this approach is that the collaborative research in direct messages is not auditable. The conversation that occurred would be useful for future reference to post a summary to the completed task. 

It would be nice if as soon as a task is started, the bot can post a link to a freshly generated telegram chat room that acts as a collaborative "work room" to solve that particular task   

Once the task is closed as complete, we can use ChatGPT to summarize the essential details from the telegram group chat and post it to the GitHub issue as a conversation summary for future reference   

Inventing the telegram integration will probably take some time so I'll set this to a week.

---

It would be nice to get automatically kicked from the chat when the task is completed so that our telegrams don't get cluttered with these.

**Comment by jordan-ae** [comment]
@0x4007  I encountered a blocker with the Telegram integration plugin. Initially, the plan was to create a bot using BotFather, similar to our previous Telegram bot. However, according to Telegram's latest documentation, bots are unable to create Telegram channels—only human users can do this, likely to prevent spamming.

To work around this limitation, I opted to use the gram-js library, which allows us to create channels via a Telegram app associated with an existing user account. The challenge here is that Telegram requires a phone number for authentication and sends a code that must be manually entered to pass 2FA. Fortunately, this authentication process only needs to be done once. After the first successful authentication, a session string is generated. This session string remains valid indefinitely unless explicitly revoked, so we won’t need to re-authenticate in the future.

Given this requirement, we'll probably have to create  a dedicated Telegram user for Ubiquity, which will be used to power the plugin.

I've made some progress and have successfully managed to create a Telegram channel when a task starts and close/delete the channel when the task is completed. I'm submitting a PR with the current state of the implementation asap.

**Comment by 0x4007** [comment]
t.me/ubiquibot is ready to use

**Comment by 0x4007** [comment]
https://t.me/UbiquityOS is ready to be used.

**Comment by Keyrxng** [comment]
QA: https://github.com/ubq-testing/telegram-bot/issues/4#issuecomment-2321198296

It is not based on https://github.com/ubiquity/ubiquibot-telegram at all and uses the `plugin-template` as a foundation. I'll create a repo I can PR against as it looks like the one I made was deleted (I'm confident that I did make it)

**Comment by 0x4007** [comment]
Perhaps there is an opportunity to use Telegram apps to solve this problem somehow.

**Comment by Keyrxng** [comment]
> Perhaps there is an opportunity to use Telegram apps to solve this problem somehow.

That's essentially what I have been trying I'm sure as the MTProto API is for clients and apps as far as I understand it while the `Bot` API is a simplified rest api.

or do you mean [mini apps](https://core.telegram.org/bots/webapps)?

**Comment by Keyrxng** [comment]
0x4007 via telegram:

> 1. Bot makes group chat
> 2. Bot posts link when task is priced. 
> 3. Task is closed and bot kicks everybody from group chat
> People manually join by using the link

---

So a new issue is created and after a price label is applied the bot creates a workroom, which is it's own telegram group chat and it posts a link to it.

At this point no one is in it so the core team member(s) assigning the labels and creating the task should be required to join the workroom immediately so there is at least one person in it in the event a contributor joins it.

Should our telegram bot also be invited into the chat directly too?

**Comment by 0x4007** [comment]
It seems that our base rate multiplier for priority levels must have been reset to default since the bot upgrade.

**Comment by Immanuel-john** [comment]
hi @0x4007 is this bounty still open to contribute? Our team got expertise in developing telegram bots and miniapps

**Comment by anonyphoenix** [comment]
It's probably not a very good idea because bots can't create chat groups. Only user accounts can. Telegram rate-limits creating chat groups and also has some limits on the number of groups a user can create.

**Comment by Keyrxng** [comment]
@0x4007 can this be assigned to me and reward generated please. As far as I can tell I have met and achieved the spec, provided ample QA, docs and tutorials to properly setup and install this plugin.

**Comment by Keyrxng** [comment]
https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/issues/11
https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/actions


https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/actions/runs/11483667259
https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/actions/runs/11483650490
https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/actions/runs/11483624489


---

Can this be assigned to me and the task completed?

**Comment by 0x4007** [comment]
@gentlementlegen i understand theres been more set up required i presume i should assign both of you

**Comment by gentlementlegen** [comment]
I spent quite some time on the setup because it is complex and @Keyrxng didn't have enough access to the configuration or the Cloudflare, but to be honest I didn't code anything in here.

**Comment by Keyrxng** [comment]
And I spent almost as much writing docs, recording tutorials and trying to assist in the setup process.

Sorry @gentlementlegen, I'm just as glad as you that it's behind us now lmao.

**Comment by gentlementlegen** [comment]
Not the first time this error pops up, I wonder if it is just OpenAI not returning the proper JSON response or the logic being flawed.

**Comment by 0x4007** [comment]
> Not the first time this error pops up, I wonder if it is just OpenAI not returning the proper JSON response or the logic being flawed.

@gentlementlegen You need to implement a fix

**Comment by 0x4007** [comment]
> The conversation that occurred would be useful for future reference to post a summary to the completed task.

I've never seen a summary posted are you sure this is implemented to spec?

**Comment by Keyrxng** [comment]
> I've never seen a summary posted are you sure this is implemented to spec?

1. That wasn't implemented no.
2. During review it wasn't mentioned and we had discussed embedding the TG conversation history etc as well and the PR was being pushed for merge so nothing else was implemented beyond initial functionality.
3. This task was really under-priced for the amount of time, effort and work involved in building the infra and the features included in https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/pull/2 compared to other from-the-ground plugins. A couple of your [comments](https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/pull/2#discussion_r1756093851) speak to that, so I'd appreciate a new clear spec and for it to be priced please.

> Pretty interesting and wild architecture where we're able to procure the benefits from both workers and actions.

> Maybe this is the future of plug-in development
