### ISSUE TITLE
Porting Capabilities

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/plugins-wishlist#5]
We have many capabilities that should be ported from the old bot code. 

Some useful ones: 

- [x] #7
- [x] #6
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12

We can break this apart into separate tasks as we get closer to implementation.

**Comment by gentlementlegen** [comment]
@0x4007 We might also want to include https://github.com/ubiquibot/assistive-pricing in the current plugins as well.

**Comment by 0x4007** [comment]
That's included under 2.
