### ISSUE TITLE
org configs sync/corrections

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os/plugins-wishlist#57]
- We have four orgs all with their own config files. 
- Each org has repos which also have their own config files (potentially)
- repo config files need to copy the entire org config (afaik) as it overwrites, not merges.

Due to the above it's very easy to have plugin URLs which are out of sync.

- [`"ubiquibot"`](https://github.com/ubiquity/.ubiquity-os/blob/c4df855b2e8670608082ad7ea4e7fcd1ef32af0d/.github/.ubiquity-os.config.yml#L20) in `command-wallet` worker URL and it should be `ubiquity-os-marketplace` or just `ubiquity-os` but the URL is valid
- [`"ubiquibot"`](https://github.com/ubiquity/.ubiquity-os/blob/c4df855b2e8670608082ad7ea4e7fcd1ef32af0d/.github/.ubiquity-os.config.yml#L29) in `command-query`, this URL is invalid as it does not match the `worker-deploy.yml` [deployment url](https://github.com/ubiquity-os-marketplace/command-query/actions/runs/11963462112)
- [`"ubiquibot"`](https://github.com/ubiquity/.ubiquity-os/blob/c4df855b2e8670608082ad7ea4e7fcd1ef32af0d/.github/.ubiquity-os.config.yml#L33) in `daemon-merging` and URL is invalid as it still points to `assistive-pricing`
- [`potential branch mismatch`](https://github.com/ubiquity/.ubiquity-os/blob/c4df855b2e8670608082ad7ea4e7fcd1ef32af0d/.github/.ubiquity-os.config.yml#L383) in `text-vector` as it targets `development` but the most recent worker was deployed to `main`.
- [`plugin instance confusion`](https://github.com/ubiquity/.ubiquity-os/blob/c4df855b2e8670608082ad7ea4e7fcd1ef32af0d/.github/.ubiquity-os.config.yml#L383) in `text-vector` as it's installed as a worker here but is running on [actions](https://github.com/ubiquity-os-marketplace/text-vector-embeddings/actions)

That is just from one org' (`ubiquity`) config file and I'm 100% certain all of them are going to have either the same or similar problems.

1. Create a plugin which detects changes to `ubiquity-os-config.yml` and then tracks all other config files and updates them accordingly.
2. Create infra to simply TG message the org admins that there is a config mismatch and it can be manually reviewed.
3. Create a workflow which effectively does the same as 1 or presents links to other configs that are mismatched within a diff comment like the `empty strings warning`?

**Comment by Keyrxng** [comment]
@rndquu @gentlementlegen @0x4007 @whilefoo rfc

**Comment by rndquu** [comment]
We should simply:
1. Remove [worker urls](https://github.com/ubiquity-os/.ubiquity-os/blob/e22141cb0682674d30a2e5f57231ca51c1ed1f5b/.github/.ubiquity-os.config.dev.yml#L3) from the configs and simply use a github `organization/repository` slug
2. Make the kernel fetch worker url from the manifest (https://github.com/ubiquity-os/plugin-template/issues/33)

**Comment by 0x4007** [comment]
> We'd better:
> 
> 1. Remove [worker urls](https://github.com/ubiquity-os/.ubiquity-os/blob/e22141cb0682674d30a2e5f57231ca51c1ed1f5b/.github/.ubiquity-os.config.dev.yml#L3) from the configs and simply use a github `organization/repository` slug
> 
> 2. Make the kernel fetch worker url from the manifest (https://github.com/ubiquity-os/plugin-template/issues/33)



- I dislike the idea of adding redundant information to the manifest 
- this disables the ability for plugins to be closed source 

It would be preferred to allow any api endpoint to be called as a plugin in the config. I think it's one of the technical benefits of our architecture vs just a glorified GitHub actions invoker.

**Comment by Keyrxng** [comment]
> - I dislike the idea of adding redundant information to the manifest
> - this disables the ability for plugins to be closed source

this is literally being implemented lmao

https://github.com/ubiquity-os/ubiquity-os-kernel/issues/224

https://github.com/ubiquity-os/plugin-template/issues/33

> I fixed the plugin installer UI dependency on matching the name so this is no longer a requirement

Yeah different issue but thanks
